- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "/home/aur_builder/yay"
    update: true
  become: yes
  become_user: aur_builder

- name: Build and install yay
  command:
    chdir: "/home/aur_builder/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
  become: yes
  become_user: aur_builder

- name: Install packages by using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - ttc-iosevka
      - teams
  become: yes
  become_user: aur_builder
