---
- name: Install chezmoi 
  community.general.pacman:
    name:
      - chezmoi
    state: present

- name: Initialize chezmoi
  command: "chezmoi init --apply --verbose {{ chezmoi_init_url }} --branch main"

- name: Update chezmoi
  command: "chezmoi update"
  tags:
  - always
