- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - xorg
    - kitty
    - git
    - bspwm
    - sxhkd
    - picom
    - nitrogen
    # - thefuck
    # - tmux
    - lsd
    # - vim
    - source-highlight
    - tree
    - base-devel
   state: present

- name: Install archival utils
  pacman:
    name:
      - atool
      - p7zip
      - unrar
      - unzip
      - xz
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
      - aria2
      - curl
      - wget
    state: present

- name: Install ImageMagick
  pacman:
    name: imagemagick
    state: present

- name: Install Programs
  pacman:
    name: 
      - chromium
      - vlc
      - gimp
    state: present
